### ISSUE TITLE
wheels will not rotate both in Gazebo and real robots when using the pholus_wheeled_motion_stack

### ISSUE THREAD

**Issue by yangweiyou** [ADVRHumanoids/centauro_cartesio#2]
The control mode set for the wheels seems to be position controlled. The attached video shows the issue.
[transform.mp4.zip](https://github.com/ADVRHumanoids/centauro_cartesio/files/4883412/transform.mp4.zip)

**Comment by yangweiyou** [comment]
The issue seems from the assigned control mode. It's always mode 1, position control. I remember for old version of XBot, wheel velocity command will be executed even in position control mode, but it's not the case for the new one.

**Comment by alaurenzi** [comment]
Hi @yangweiyou , and sorry for the late reply. Try to add the [following lines](https://github.com/ADVRHumanoids/centauro_cartesio/blob/96c45d814f136c2880afa0c6dd4f6b92493aa60c/launch/centauro_car_model.launch#L24) to the launch file (maybe some joint name needs to be changed from Centauro to Pholus). Let me know it this solves your issue.

**Comment by yangweiyou** [comment]
Hi @alaurenzi , thanks for the reply! I found the centauro_cartesio has been changed a lot from the version we are using. We do have similar lines as you mentioned and already make it consistent with Pholus as below:
    <param name="cartesian/problem_description" textfile="$(find pholus_cartesio)/pholus_wheeled_motion_stack.yaml"/>
        
    <rosparam ns="cartesian/velocity_whitelist">
        <param>[fr_wheel_joint, fl_wheel_joint, hr_wheel_joint, hl_wheel_joint]</param>
    </rosparam>

But the wheels will be set to position control mode and not move.

**Comment by yangweiyou** [comment]
Figure it out, it's param instead of rosparam to set the velocity whitelist
