### ISSUE TITLE
Must I use centauro car model to move the pelvis up and down?

### ISSUE THREAD

**Issue by torydebra** [ADVRHumanoids/centauro_cartesio#4]
With the simplified model and stack (no virtual car chain) I can correctly move the wheels to shift the whole robot in the x and y linear direction and rotate along z.

I noticed that I can not move the pelvis up and down or rotate in different directions than z : the whole model will move "flying" and loosing the contact with the floor, instead bending the legs, for example, for squatting.

So to have this behavious must I use the car model with the virtual chain ?

Thanks @alaurenzi  @liesrock

**Comment by liesrock** [comment]
Ciao @torydebra, did the test happened on gazebo or rviz? Can you report here the stack you are using?

**Comment by torydebra** [comment]
Yes sorry for lack of details,

I am launching it with : `roslaunch centauro_cartesio_config centauro_wheeled_motion.launch gui:=true`

which uses the `<param name="cartesian/problem_description" textfile="$(find centauro_cartesio_config)/centauro_wheeled_motion_stack.yaml"/>` stack:
```yaml
    - ["Waist",  "Wheel_FL", "Wheel_FR", "Wheel_HR", "Wheel_HL", "Steering_FL", "Steering_FR", "Steering_HL","Steering_HR", "LeftArm", "RightArm"] #, "Gaze"]
    - ["Rolling_FL", "Rolling_FR","Rolling_HL","Rolling_HR","Ankle_FL", "Ankle_FR", "Ankle_HR", "Ankle_HL"]
    - ["Postural"]
 ```

And it happens both with and without gazebo. The model is dragged around even up and down instead of straightening and bending or  the legs, probably only the transformation between world and pelvis is changed. 
So the robot (simulated) can not follow this and stay still

**Comment by alaurenzi** [comment]
That's normal, since you don't have any task to enforce a physically consistent contact...

**Comment by torydebra** [comment]
Ok, I am using the car model anyway, recently
