### ISSUE TITLE
Centauro cartesian Car task acts weird

### ISSUE THREAD

**Issue by torydebra** [ADVRHumanoids/centauro_cartesio#6]
What I am trying to do is to prevent impossible movements of the robot (car_frame version) even in dummy mode. 
The dummy robot should not "fly": I would like to prevent translation on z and rotations on x and y.

 I am trying to playing with the `indices` of the task:
```yaml
Car:
    type: "Cartesian"
    distal_link: pelvis
    name: "locomotion"
    lambda: 0.1
    indices: [???]
```

But indices does not correspond to what I expect. For example:
-`indices: [0]`: the robot can only roll forward (doing a rototranslation: linear x and rotation y)
-`indices: [1]`: the robot can only roll laterally (doing a rototranslation: linear y and rotation x)
-`indices: [2]`: the robot can only go up and down (linear z)
-`indices: [3]`, `indices: [4]`, `indices: [5]`: it seems that any kind of motion is prevented (even with `indices: [3, 4, 5]`)

What I expect was, like for an cartesian arm task, to put [0 1 2] to make the task satisfy only the linear part of the goal, and [3 4 5] to satisfy only the rotational part of the goal (or at least viceversa)
In this case it seems that rotations and translations are mixed up in the single indices

Am I doing something wrong?
@liesrock @alaurenzi

**Comment by alaurenzi** [comment]
Yes, the `indices` field serves the [purpose of extracting a subtask from a given task](https://advrhumanoids.github.io/CartesianInterface/problemdesc.html#indices). Therefore, the "locomotion" task as you named it won't control the rows that don't appear in the `indices` field. If you set, say, `indices: [0]`, it means that y, z, roll, pitch and yaw are up to the solver to decide, and are affected by all the other tasks, plus the regularization.

If you don't want a frame to move about the `z` direction, compute your reference accordingly, or set a constraint with the indices you want to constrain.

**Comment by torydebra** [comment]
Ok understood thanks!
